// Mock data for the Movie Insights app

export const mockMovieData = [
  {
    movie_id: 1,
    movie_name: "The Shawshank Redemption",
    genre: "Drama",
    movie_duration: 142,
    plot_summary:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    movie_link_imdb: "https://www.imdb.com/title/tt0111161/",
    language: "English",
    country: "USA",
    budget: 25000000,
    title_year: 1994,
    imdb_score: 9.3,
    aspect_ratio: "1.85:1",
    movie_release_date: "1994-10-14",
    number_of_days_in_theatre: 180,
    movie_certification: "R",
    movie_color_print: "Color",
    number_of_actors: 15,
    obtained_by_OTT_platform: "Netflix",
    director_id: 1,
  },
  {
    movie_id: 2,
    movie_name: "The Godfather",
    genre: "Crime",
    movie_duration: 175,
    plot_summary:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    movie_link_imdb: "https://www.imdb.com/title/tt0068646/",
    language: "English",
    country: "USA",
    budget: 6000000,
    title_year: 1972,
    imdb_score: 9.2,
    aspect_ratio: "1.85:1",
    movie_release_date: "1972-03-24",
    number_of_days_in_theatre: 210,
    movie_certification: "R",
    movie_color_print: "Color",
    number_of_actors: 20,
    obtained_by_OTT_platform: "Amazon Prime",
    director_id: 2,
  },
  {
    movie_id: 3,
    movie_name: "Pulp Fiction",
    genre: "Crime",
    movie_duration: 154,
    plot_summary:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    movie_link_imdb: "https://www.imdb.com/title/tt0110912/",
    language: "English",
    country: "USA",
    budget: 8000000,
    title_year: 1994,
    imdb_score: 8.9,
    aspect_ratio: "2.39:1",
    movie_release_date: "1994-10-14",
    number_of_days_in_theatre: 175,
    movie_certification: "R",
    movie_color_print: "Color",
    number_of_actors: 12,
    obtained_by_OTT_platform: "Netflix",
    director_id: 3,
  },
  {
    movie_id: 4,
    movie_name: "The Dark Knight",
    genre: "Action",
    movie_duration: 152,
    plot_summary:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    movie_link_imdb: "https://www.imdb.com/title/tt0468569/",
    language: "English",
    country: "USA",
    budget: 185000000,
    title_year: 2008,
    imdb_score: 9.0,
    aspect_ratio: "2.39:1",
    movie_release_date: "2008-07-18",
    number_of_days_in_theatre: 220,
    movie_certification: "PG-13",
    movie_color_print: "Color",
    number_of_actors: 25,
    obtained_by_OTT_platform: "HBO Max",
    director_id: 4,
  },
  {
    movie_id: 5,
    movie_name: "Inception",
    genre: "Sci-Fi",
    movie_duration: 148,
    plot_summary:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    movie_link_imdb: "https://www.imdb.com/title/tt1375666/",
    language: "English",
    country: "USA",
    budget: 160000000,
    title_year: 2010,
    imdb_score: 8.8,
    aspect_ratio: "2.39:1",
    movie_release_date: "2010-07-16",
    number_of_days_in_theatre: 190,
    movie_certification: "PG-13",
    movie_color_print: "Color",
    number_of_actors: 18,
    obtained_by_OTT_platform: "Netflix",
    director_id: 4,
  },
  {
    movie_id: 6,
    movie_name: "Parasite",
    genre: "Thriller",
    movie_duration: 132,
    plot_summary:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    movie_link_imdb: "https://www.imdb.com/title/tt6751668/",
    language: "Korean",
    country: "South Korea",
    budget: 11400000,
    title_year: 2019,
    imdb_score: 8.6,
    aspect_ratio: "2.39:1",
    movie_release_date: "2019-10-11",
    number_of_days_in_theatre: 165,
    movie_certification: "R",
    movie_color_print: "Color",
    number_of_actors: 10,
    obtained_by_OTT_platform: "Hulu",
    director_id: 5,
  },
  {
    movie_id: 7,
    movie_name: "The Matrix",
    genre: "Sci-Fi",
    movie_duration: 136,
    plot_summary:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    movie_link_imdb: "https://www.imdb.com/title/tt0133093/",
    language: "English",
    country: "USA",
    budget: 63000000,
    title_year: 1999,
    imdb_score: 8.7,
    aspect_ratio: "2.39:1",
    movie_release_date: "1999-03-31",
    number_of_days_in_theatre: 200,
    movie_certification: "R",
    movie_color_print: "Color",
    number_of_actors: 15,
    obtained_by_OTT_platform: "HBO Max",
    director_id: 6,
  },
  {
    movie_id: 8,
    movie_name: "Forrest Gump",
    genre: "Drama",
    movie_duration: 142,
    plot_summary:
      "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    movie_link_imdb: "https://www.imdb.com/title/tt0109830/",
    language: "English",
    country: "USA",
    budget: 55000000,
    title_year: 1994,
    imdb_score: 8.8,
    aspect_ratio: "2.39:1",
    movie_release_date: "1994-07-06",
    number_of_days_in_theatre: 230,
    movie_certification: "PG-13",
    movie_color_print: "Color",
    number_of_actors: 20,
    obtained_by_OTT_platform: "Netflix",
    director_id: 7,
  },
]

export const mockDirectorData = [
  {
    director_id: 1,
    director_name: "Frank Darabont",
    date_of_birth: "1959-01-28",
    director_famous_movies: "The Shawshank Redemption, The Green Mile",
  },
  {
    director_id: 2,
    director_name: "Francis Ford Coppola",
    date_of_birth: "1939-04-07",
    director_famous_movies: "The Godfather, Apocalypse Now",
  },
  {
    director_id: 3,
    director_name: "Quentin Tarantino",
    date_of_birth: "1963-03-27",
    director_famous_movies: "Pulp Fiction, Django Unchained",
  },
  {
    director_id: 4,
    director_name: "Christopher Nolan",
    date_of_birth: "1970-07-30",
    director_famous_movies: "The Dark Knight, Inception, Interstellar",
  },
  {
    director_id: 5,
    director_name: "Bong Joon Ho",
    date_of_birth: "1969-09-14",
    director_famous_movies: "Parasite, Snowpiercer",
  },
  {
    director_id: 6,
    director_name: "Lana and Lilly Wachowski",
    date_of_birth: "1965-06-21",
    director_famous_movies: "The Matrix, Cloud Atlas",
  },
  {
    director_id: 7,
    director_name: "Robert Zemeckis",
    date_of_birth: "1952-05-14",
    director_famous_movies: "Forrest Gump, Back to the Future",
  },
]

export const mockActorData = [
  {
    actor_id: 1,
    actor_name: "Tim Robbins",
    actor_date_of_birth: "1958-10-16",
    actor_famous_movie: "The Shawshank Redemption",
    movie_ids: [1],
  },
  {
    actor_id: 2,
    actor_name: "Morgan Freeman",
    actor_date_of_birth: "1937-06-01",
    actor_famous_movie: "The Shawshank Redemption",
    movie_ids: [1],
  },
  {
    actor_id: 3,
    actor_name: "Marlon Brando",
    actor_date_of_birth: "1924-04-03",
    actor_famous_movie: "The Godfather",
    movie_ids: [2],
  },
  {
    actor_id: 4,
    actor_name: "Al Pacino",
    actor_date_of_birth: "1940-04-25",
    actor_famous_movie: "The Godfather",
    movie_ids: [2],
  },
  {
    actor_id: 5,
    actor_name: "John Travolta",
    actor_date_of_birth: "1954-02-18",
    actor_famous_movie: "Pulp Fiction",
    movie_ids: [3],
  },
  {
    actor_id: 6,
    actor_name: "Samuel L. Jackson",
    actor_date_of_birth: "1948-12-21",
    actor_famous_movie: "Pulp Fiction",
    movie_ids: [3],
  },
  {
    actor_id: 7,
    actor_name: "Christian Bale",
    actor_date_of_birth: "1974-01-30",
    actor_famous_movie: "The Dark Knight",
    movie_ids: [4],
  },
  {
    actor_id: 8,
    actor_name: "Heath Ledger",
    actor_date_of_birth: "1979-04-04",
    actor_famous_movie: "The Dark Knight",
    movie_ids: [4],
  },
  {
    actor_id: 9,
    actor_name: "Leonardo DiCaprio",
    actor_date_of_birth: "1974-11-11",
    actor_famous_movie: "Inception",
    movie_ids: [5],
  },
  {
    actor_id: 10,
    actor_name: "Joseph Gordon-Levitt",
    actor_date_of_birth: "1981-02-17",
    actor_famous_movie: "Inception",
    movie_ids: [5],
  },
  {
    actor_id: 11,
    actor_name: "Song Kang-ho",
    actor_date_of_birth: "1967-01-17",
    actor_famous_movie: "Parasite",
    movie_ids: [6],
  },
  {
    actor_id: 12,
    actor_name: "Lee Sun-kyun",
    actor_date_of_birth: "1975-03-02",
    actor_famous_movie: "Parasite",
    movie_ids: [6],
  },
  {
    actor_id: 13,
    actor_name: "Keanu Reeves",
    actor_date_of_birth: "1964-09-02",
    actor_famous_movie: "The Matrix",
    movie_ids: [7],
  },
  {
    actor_id: 14,
    actor_name: "Laurence Fishburne",
    actor_date_of_birth: "1961-07-30",
    actor_famous_movie: "The Matrix",
    movie_ids: [7],
  },
  {
    actor_id: 15,
    actor_name: "Tom Hanks",
    actor_date_of_birth: "1956-07-09",
    actor_famous_movie: "Forrest Gump",
    movie_ids: [8],
  },
  {
    actor_id: 16,
    actor_name: "Robin Wright",
    actor_date_of_birth: "1966-04-08",
    actor_famous_movie: "Forrest Gump",
    movie_ids: [8],
  },
]

export const mockReviewData = [
  {
    review_id: 1,
    reviewer_name: "Roger Ebert",
    review_content:
      "One of the most beloved American films, this prison drama is a testament to the human spirit and friendship.",
    review_date: "1994-10-17",
    rating: 9.5,
    movie_id: 1,
  },
  {
    review_id: 2,
    reviewer_name: "Peter Travers",
    review_content: "A modern classic that continues to resonate with audiences of all ages.",
    review_date: "1994-11-05",
    rating: 9.0,
    movie_id: 1,
  },
  {
    review_id: 3,
    reviewer_name: "Roger Ebert",
    review_content: "The benchmark for crime films and an enduring masterpiece of American cinema.",
    review_date: "1972-03-24",
    rating: 10.0,
    movie_id: 2,
  },
  {
    review_id: 4,
    reviewer_name: "Gene Siskel",
    review_content: "A perfect film in every way, with performances that define careers.",
    review_date: "1972-04-02",
    rating: 9.8,
    movie_id: 2,
  },
  {
    review_id: 5,
    reviewer_name: "Roger Ebert",
    review_content: "A bold, innovative film that redefined narrative structure in cinema.",
    review_date: "1994-10-14",
    rating: 9.0,
    movie_id: 3,
  },
  {
    review_id: 6,
    reviewer_name: "Janet Maslin",
    review_content: "Tarantino's masterpiece remains as fresh and exciting as when it first premiered.",
    review_date: "1994-10-20",
    rating: 8.5,
    movie_id: 3,
  },
  {
    review_id: 7,
    reviewer_name: "Roger Ebert",
    review_content: "A superhero film that transcends its genre to become a compelling crime drama.",
    review_date: "2008-07-18",
    rating: 9.5,
    movie_id: 4,
  },
  {
    review_id: 8,
    reviewer_name: "A.O. Scott",
    review_content: "Heath Ledger's performance as the Joker is a tour de force that elevates the entire film.",
    review_date: "2008-07-24",
    rating: 9.0,
    movie_id: 4,
  },
  {
    review_id: 9,
    reviewer_name: "Roger Ebert",
    review_content: "A mind-bending thriller that challenges viewers while delivering spectacular visuals.",
    review_date: "2010-07-15",
    rating: 9.0,
    movie_id: 5,
  },
  {
    review_id: 10,
    reviewer_name: "Peter Travers",
    review_content:
      "Nolan's most ambitious film to date, with a concept that's as emotionally resonant as it is intellectually stimulating.",
    review_date: "2010-07-12",
    rating: 9.5,
    movie_id: 5,
  },
]

export const mockAwardData = [
  {
    award_id: 1,
    award_name: "Academy Award for Best Picture",
    award_year_given: 1995,
    number_of_votes: 5000,
    movie_id: 1,
  },
  {
    award_id: 2,
    award_name: "Academy Award for Best Adapted Screenplay",
    award_year_given: 1995,
    number_of_votes: 4800,
    movie_id: 1,
  },
  {
    award_id: 3,
    award_name: "Academy Award for Best Picture",
    award_year_given: 1973,
    number_of_votes: 6000,
    movie_id: 2,
  },
  {
    award_id: 4,
    award_name: "Academy Award for Best Actor",
    award_year_given: 1973,
    number_of_votes: 5500,
    movie_id: 2,
  },
  {
    award_id: 5,
    award_name: "Academy Award for Best Original Screenplay",
    award_year_given: 1995,
    number_of_votes: 4700,
    movie_id: 3,
  },
  {
    award_id: 6,
    award_name: "Palme d'Or at Cannes Film Festival",
    award_year_given: 1994,
    number_of_votes: 3000,
    movie_id: 3,
  },
  {
    award_id: 7,
    award_name: "Academy Award for Best Supporting Actor",
    award_year_given: 2009,
    number_of_votes: 5800,
    movie_id: 4,
  },
  {
    award_id: 8,
    award_name: "BAFTA Award for Best Film",
    award_year_given: 2009,
    number_of_votes: 4200,
    movie_id: 4,
  },
  {
    award_id: 9,
    award_name: "Academy Award for Best Visual Effects",
    award_year_given: 2011,
    number_of_votes: 5200,
    movie_id: 5,
  },
  {
    award_id: 10,
    award_name: "Academy Award for Best Cinematography",
    award_year_given: 2011,
    number_of_votes: 4900,
    movie_id: 5,
  },
]
